### ISSUE TITLE
State Template Using Markdown

### ISSUE THREAD

**Issue by coop333** [Office-of-Digital-Innovation/California-State-Web-Template#143]
@kkoryaka , would the Department of Technology be interested in having a template that uses markdown for content pages? This is precisely what we at the Bureau of Automotive Repair have done and it has worked out quite well. It allows our department that handles content for our website to make changes without needing to know much about websites. 

If interested let me know and I can share a stripped down version of the template.
[BAR Home Page](https://bar.ca.gov) - This pages uses HTML, but there are portions of the page that are written in Markdown and controlled by our content department.
[Page using all markdown with page navigation](https://bar.ca.gov/Industry/STAR_Program/FAQ)
[Page using all markdown with a right side nav for related links](https://bar.ca.gov/Industry/Training)
[Standard page using all markdown](https://bar.ca.gov/BAR_Advisory_Group)

**Comment by kkoryaka** [comment]
@coop333 this is cool idea, but at this State Template's main purpose is to provide essential web template framework and codebase in the most common way (HTML, CSS and JavaScript) to ensure a uniform user experience across state entities.  If any department finds that any other technology (such as markdown in your case) works for them better and makes their workflow easier and more efficient more power to them. Thanks you for sharing, thought. We actually in the process of adapting markdown use in our department for documentation.
