### ISSUE TITLE
Custom element instead of native HTML?

### ISSUE THREAD

**Issue by kkroon** [Office-of-Digital-Innovation/California-State-Web-Template#184]
In the latest update to the accordion component, I noticed that the template now recommends a custom HTML tag (cagov-accordion) rather than the native [HTML details element](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element).

Can you explain what the rationale for this decision?

**Comment by kkoryaka** [comment]
We are slowly integrating a new California design system that is going to be build with new components that are:
- Based on W3C custom element standards to avoid the need for an underlying library
- Created with performance and accessibility in mind
- Usable in any framework
Accordion is one of those new design system's components that is using custom elements. The design system is still in beta mode. We will make initial design system presentation to State web community in our next DWSN meeting.

**Comment by kkroon** [comment]
Perhaps I'm just dense, but I'm having a hard time understanding how this:
`<cagov-accordion>
    <div class="cagov-accordion-card">
      <button class="accordion-card-header accordion-alpha" type="button" aria-expanded="false">
        <div class="accordion-title">Lorem ipsum</div>
        <div class="plus-minus">
          <cagov-plus>
            <div class="accordion-icon" aria-hidden="true">
              <svg viewbox="0 0 25 25">
                <title>Plus</title>
                <line x1="6" y1="12.5" x2="19" y2="12.5" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" vector-effect="non-scaling-stroke" />
                <line y1="6" x1="12.5" y2="19" x2="12.5" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" vector-effect="non-scaling-stroke" />
              </svg>
            </div>
          </cagov-plus>
          <cagov-minus>
            <div class="accordion-icon" aria-hidden="true">
              <svg viewbox="0 0 25 25">
                <title>Minus</title>
                <line x1="6" y1="12.5" x2="19" y2="12.5"  fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" vector-effect="non-scaling-stroke" />
              </svg>
            </div>
          </cagov-minus>
        </div>
      </button>
      <div class="accordion-card-container" aria-hidden=" true" style="height: 0px;">
        <div class="card-body">
          <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf
            moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
            Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda
            shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea
            proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim
            aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.</p>
        </div>
      </div>
    </div>
</cagov-accordion>`

— plus a JavaScript function that's **required** to make it work is objectively better than —

`<details>
    <summary>Lorem ipsum</summary>
          <p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf
            moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
            Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda
            shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea
            proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim
            aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.</p>
</details>`

which enjoys [strong support in almost all browsers](https://caniuse.com/?search=details-element), does not require any JavaScript, with a disclosure widget that can be styled with plain CSS — and the experience in the one browser that does not support it (Internet Explorer) degrades gracefully to fully accessible content.

**Comment by rkojik** [comment]
I'm just useless overhead so my opinion doesn't matter all that much, however I'm with Kurtis on this one... I haven't experimented with the details element... but I've much preferred progressive enhancement > custom components for accordions: https://inclusive-components.design/collapsible-sections/. If JavaScript is disabled, we're left with headings and text (which is, at it's core, all that collapsible sections are)

**Comment by aaronhans** [comment]
This is a good point. I like the approach you've pointed out @kkroon! That is some very clean markup. The difference is that the accordion custom element animates its transitions.

**Comment by kkroon** [comment]
@aaronhans
A quick search on the web shows one way to [animate the details element using that plain ol' CSS I mentioned above](https://css-tricks.com/how-to-animate-the-details-element/) ...

**Comment by aaronhans** [comment]
Thanks @kkroon! I love that we are getting expert feedback like yours with simplification suggestions. We definitely have the opportunity to streamline this component. That is a great article you linked. It does use js for the animation too but it may be better to forgo the animation in favor of code simplicity.

**Comment by artuoma** [comment]
@kkroon I think there is a balance and fine line between pure functionality and good design. For example a lot of that code is ensuring the target area is large enough for mobile use and that those targets are visually obvious for a good user experience.

**Comment by kkroon** [comment]
@artuoma
Okay, then:

- make it bigger (font-size: larger)
- Make it bold (font-weight: bold)
- Style it with a marker after, rather than before.
- Or replace the marker with a background image (good place for your SVGs)

**Comment by kkoryaka** [comment]
@kkroon you are welcome to make your suggestions directly in Design System repo https://github.com/cagov/design-system since State Template is consuming this component from there, it would be good opportunity for you interact with and give your feedback directly to design system engineers.

**Comment by artuoma** [comment]
@kkoryaka can you post the link to that component here?

**Comment by aaronhans** [comment]
I think changing the markup to use the details & summary element would be an immediate improvement. Right now the behavior if the js doesn't load/execute is that it stays open and can't collapse so using those elements is a nice improvement.

@xjensen pointed out the open attribute being added to the details tag we can hang the animations on. We can experiment with this and see if we can figure out pure css opening and closing animations on elements of unknown height. Pointers here are welcome.

**Comment by kkoryaka** [comment]
https://github.com/cagov/design-system/tree/main/components/accordion
