### ISSUE TITLE
Update accordion component in beta with the latest code from Design System

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#199]
Update accordion component in beta with the latest code from Design System
- Update styles in src/scss/cagov/accordion.scss
- Update JS code in scs/js/cagov/accordion.js
https://designsystem.webstandards.ca.gov/components/accordion/readme/

**Comment by kkoryaka** [comment]
@Courtney-Chittock I have updated focus state. Please review in staging: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/accordions.html

**Comment by Courtney-Chittock** [comment]
@kkoryaka you're a genius! This looks amazing. I am signing off. What is the next step to making this a component?

**Comment by kkoryaka** [comment]
@Courtney-Chittock next step would be to bring this update to the Design System. We will move forward with this one on Beta, I will add this issue to the QA column in our board.
