### ISSUE TITLE
Review "Structure" page updated content

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#217]
Review and provide suggested edits for the Structure page updated content: (in beta staging)
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/structure.html

Original page to compare: https://beta.template.webstandards.ca.gov/structure.html

**Comment by kkoryaka** [comment]
@ashleydraper This page is moved into Get Started page. Closing the issue.

**Comment by ashleydraper** [comment]
I see the movement. Okay, thanks for the update @kkoryaka
