### ISSUE TITLE
Add Step List component

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#222]
Add step list component to the State Web Template that would resemble  Design System's Step List component 

https://designsystem.webstandards.ca.gov/components/step-list/readme/

Screenshot example:
![Screen Shot 2022-03-25 at 9 01 09 AM](https://user-images.githubusercontent.com/31669748/160157213-d1a742f5-9fe1-4a5b-956a-58b5f9306055.png)

**Comment by kkoryaka** [comment]
Notify @ashleydraper when it's done

**Comment by Greg-Watanabe** [comment]
@ashleydraper This is done:
https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/tree/6.0.8-steplist-222

**Comment by ashleydraper** [comment]
@kkoryaka I don't see the step list as pictured above on the "[what's new](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/getting-started.html)" page in dev. Can you point me to where this was done? Like what page?

**Comment by kkoryaka** [comment]
@ashleydraper it is this page: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/update.html
If you still don't see step list make hard refresh so new css is loaded into your cache,

**Comment by yesenia-gtz** [comment]
@ashleydraper is this ok to close? I see a note from @Greg-Watanabe that is is done.

**Comment by ashleydraper** [comment]
@yesenia-gtz Yes we can close, we are now tracking progress in [issue #410] 
(https://github.com/Office-of-Digital-Innovation/California-State-Web-Template/issues/410).
