### ISSUE TITLE
Information Architecture and Content flow (State Template 6.0)

### ISSUE THREAD

**Issue by yesenia-gtz** [Office-of-Digital-Innovation/California-State-Web-Template#232]
**State Template 6.0 Content & Design Strategy needs**
- [x] Restructure information architecture 
- [x] Align component pages to Design System
- [ ] Audit all content pages

Success criteria:
- Content is written in plain language
- The site structure is easy to navigate and is user friendly

**COMPLETION TARGET:**
 4/20/2022

**Comment by ashleydraper** [comment]
@artuoma @yesenia-gtz We are still finalizing copy for the menu names, but after meeting with Kon, we've landed on the IA represented in the upper far right of this [lucid board](https://lucid.app/lucidchart/dd496664-627a-4e71-b330-9a10a596ea79/edit?invitationId=inv_52a2808a-e70d-4155-9193-5cf2aaaa3573&page=0_0#).
Let me know if we should meet, otherwise, Courtney and I will continue on this path.

**Comment by ashleydraper** [comment]
For the content audit, we can use this [state template 6.0 google folder](https://drive.google.com/drive/u/3/folders/1fLv2GDW_X3OCx4MkthWabGvJnH_INIOn) where all google staging docs are housed.

**Comment by yesenia-gtz** [comment]
@ashleydraper @Courtney-Chittock  thank you for putting the IA together, this is fantastic! Continue on :)

**Comment by ashleydraper** [comment]
With @artuoma and @yesenia-gtz's blessings, @Courtney-Chittock and I are moving ahead with our [proposed IA](https://lucid.app/lucidchart/dd496664-627a-4e71-b330-9a10a596ea79/edit?invitationId=inv_52a2808a-e70d-4155-9193-5cf2aaaa3573&page=0_0#). 
By virtue of merging certain pages together, and re-designing all of the content, we'll be able to address the content audit concurrently.

**Comment by extinah** [comment]
Great :) Other than a sneak peek, would love a tour sometime. Looks wonderful!

**Comment by ashleydraper** [comment]
@extinah You got it! I'll be sure to invite you to our next discussion.

**Comment by ashleydraper** [comment]
4/19- Conducted user interview with Mike Adams from EDD

- Noted that external folks can only access legacy site
- Never clicked on "getting started" (maybe the very first time visiting the site, but never again)
- Returning end users already know what they are doing, they tend to move toward "what's new" very quickly
- Feel no need to click "getting started" as that is more beginner content

**Comment by ashleydraper** [comment]
Full component list:
[Accordions](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/accordions.html)
[Alert Banner](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/alert-banner.html)
[Banner](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/large-header-banner.html)
[Breadcrumb](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/breadcrumb.html)
[Buttons](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/buttons.html)
[Countdown](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/countdown.html)
[Featured Narrative](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/featured-narrative.html)
[Featured Search](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/featured-search.html)
[Form Styles](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/form.html)
[Horizontal Rules](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/horizontal-rules.html)
[Lists](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/lists.html)
[Modal](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/modal.html)
[Number Counter](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/number-counter.html)
[Progress Bars](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/progress-bars.html)
[Progress Blocks](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/progress-blocks.html)
[SocialSharer](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/socialsharer.html)
[Step List](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/step-list.html)
[Tabs](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/tabs.html)
[Tables](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/tables.html)
[Timeline](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/timeline.html)
Navigation
[Full Width/Active Search](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/navigation-full-width-utility.html)
[Flex Megamenu](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/navigation-megamenu-flex.html)
[Single Level](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/navigation-single.html)
[Dropdown](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/navigation-dropdown.html)
[Page Navigation](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/page-navigation.html)
[Side Menu](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/navigation-sidebar.html)
CSS Units
[CSS Shortcuts](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/shortcuts.html)
[Gradient Backgrounds](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/gradient-backgrounds.html)
[Icons](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/icon-fonts.html)
[Text Accent](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/text-accent.html)
[Spacing](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/spacing.html)

**Comment by Courtney-Chittock** [comment]
All **Navigation** items are on a separate webpage.
Nothing under **CSS Units** is a component, and those items are already on separate webpages or will need to be integrated where appropriate if I missed them during the initial layout. 
If we want to consider putting everything under Components we will likely need to get some other experts in the room.

**Comment by ashleydraper** [comment]
I copied this list from our [beta staging environment](https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/accordions.html)- this may need some updating for sure.
Nevertheless, I've never been supportive of a page titled "navigation" in our nav menu. These components are very different from the navigation components in the design system, but I do appreciate them under the "components" parent page. 
I'll edit CSS units out of this list.

**Comment by ashleydraper** [comment]
@kkoryaka Will you please add Koji and Blaine to this repo? They should be assigned to this issue.

**Comment by ashleydraper** [comment]
@kkoryaka The **[accordion component](https://docs.google.com/document/d/11GtQjhuwab5f0Xw-t1ksxuKhaKMzjhXBtEuNYbQ3yrk/edit#heading=h.w5y788277lx5)** has been reviewed. Let's more to staging.

**Comment by kkoryaka** [comment]
@ashleydraper separate this issue into separate issue for each page

**Comment by ashleydraper** [comment]
Archiving this issue. Look to component-specific issues for granular detail and tracking through the approval process.
