### ISSUE TITLE
Redesign badge element, so it doesn't look like button

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#272]
Current badge:
![Screen Shot 2022-05-04 at 4 42 36 PM](https://user-images.githubusercontent.com/31669748/166842467-a7e9000c-cb9b-4fa8-8270-acd0465b42a1.png)

Proposed:
![Screen Shot 2022-05-04 at 4 41 47 PM](https://user-images.githubusercontent.com/31669748/166842479-f54339e6-b227-46ac-a261-d277e732aa2d.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka I like the direction you are going in. Two recommendations:
1. Keep "Note:" text the same size as the paragraph text. That way, people who can't perceive the highlight color will still see the bolded text, and the text won't appear smaller than the surrounding text (which can deemphasize it).
2. Use an Oceanside color to highlight the text so it stands out more to users who can perceive color (this will also help prevent the badge from looking like a disabled button).

Example:
![image](https://user-images.githubusercontent.com/99773875/171509356-ee1b567a-090d-40dd-a7f0-7d722b77a813.png)

**Comment by Courtney-Chittock** [comment]
@rkojik it's more of a highlight? But yes, it's not quite like, say, social media badges. My main concern was that it looked like a button before. Open to ideas for renaming.

**Comment by rkojik** [comment]
Yeah, the example is more of a highlight or emphasis—and the clicky-ness is a common problem with traditional badges as well. I think the general fix is to give it a larger border radius than the buttons, so to make it more of a 'pill' shape (for visual users, that is).

**Comment by kkoryaka** [comment]
@Courtney-Chittock  I have renamed badge class to text-highlight. And added your variations to this css units page: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/text-accent.html
