### ISSUE TITLE
Update "Template Updates" page content  

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#282]
Update  "Template Updates" content and flow based on figma wireframe:
https://www.figma.com/file/MqZcuRodjzKf03BTnQw2KS/Beta-Redesign-Sandbox?node-id=4%3A34

**Comment by kkoryaka** [comment]
Use updates from this doc: https://docs.google.com/document/d/15_Qr6ahAbD_L4S-pnl8707AWRRRsS8RZI3EAeFKGRbM/edit#heading=h.c8f4g69ygif0

**Comment by kkoryaka** [comment]
@ashleydraper  Please check updated page. I did my part. You can massage the language and make it sound good now: https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/update.html

**Comment by ashleydraper** [comment]
@kkoryaka 
![image](https://user-images.githubusercontent.com/62437425/168367314-fb8ee2fd-4c04-4b97-a27c-7708e6a90f2b.png)
