### ISSUE TITLE
Add component illustrations on component, patterns, css units pages

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#305]
- Create illustration (icon) for each available component, content pattern, and css unit
- Create cards with those illustration inside of components and content pattern landing pages and link those cards to each corresponding component or content pattern page.
- Add short  description for each component/pattern into those cards.

Screenshot example:
![Screen Shot 2022-05-26 at 8 43 23 AM](https://user-images.githubusercontent.com/31669748/170524186-f8ed5555-7baa-49bf-bb28-27b9f5d10a32.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka Please see [these Figma boards](https://www.figma.com/file/pGKEwXZeilHOCNI4bR5ffe/State-Template-V6-Release?node-id=389%3A3215) with my feedback on the illustrations.

**Comment by kkoryaka** [comment]
@Courtney-Chittock I have updated illustrations on components, templates, css units, structure and navigation samples pages

**Comment by Courtney-Chittock** [comment]
@kkoryaka this is looking good. Please address the following feedback:

- Make sure all graphics are the same total size. (In the sample selection on the right, sizes are not consistent).
- Make Accordion graphic smaller on grey background; it is not a full-page component.
- Update Blockquote to resemble actual SWT blockquote design.
- Make Table graphic smaller on grey background; it is not a full-page component.
- Fix Parallax graphic

Let me know if you want to huddle and discuss.

**Comment by kkoryaka** [comment]
@Courtney-Chittock those 4 icons are now fixed based on your redesigned versions. Please review. 
![Screen Shot 2022-07-05 at 3 34 29 PM](https://user-images.githubusercontent.com/31669748/177428264-9b16af01-8214-4926-a61b-77b13e8617e3.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka looks good, thanks! I think I can close this one out.
