### ISSUE TITLE
Update breadcrumbs component to resemble figma mockup

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#324]
- Update breadcrumbs component to resemble figma mockup
- Create dynamic eleventy breadcrumbs include in State Template layouts
![Screen Shot 2022-06-03 at 9 10 02 AM](https://user-images.githubusercontent.com/31669748/171904104-7e6097d9-c8a4-4f41-bc64-be324fff08f4.png)

**Comment by kkoryaka** [comment]
![Screen Shot 2022-06-07 at 1 06 12 PM](https://user-images.githubusercontent.com/31669748/172472846-4254fc38-9db9-4416-89eb-fcd3e3516e11.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock Assigning it to you for review.

**Comment by Courtney-Chittock** [comment]
@kkoryaka are you able to set up a test page with a really long string of crumbs so I can assess the behavior on various screen sizes?

**Comment by kkoryaka** [comment]
@Courtney-Chittock I can show you how you can add more text by using dev tool.

**Comment by Courtney-Chittock** [comment]
@kkoryaka I was able to add links in the browser editor. The breadcrumbs look like they do in the Design System Figma board. I think we are good to close this out.
