### ISSUE TITLE
Improve tab panel mobile behavior

### ISSUE THREAD

**Issue by Courtney-Chittock** [Office-of-Digital-Innovation/California-State-Web-Template#350]
Currently on mobile tab panels collapse into accordion-style boxes but without accordion styling to tell users the boxes can be expanded and collapsed.

![image](https://user-images.githubusercontent.com/99773875/173904149-abecb6bf-b195-47f7-aca8-756b82ee67b1.png)

To increase affordance and usability of expand/collapse functionality:

- Add carat on the left of the label similar in styling and functionality to the accordion caret.
- Make entire box clickable (focus should reflect that).
- Add hover effect to box (darker grey like left side of accordion on hover).
- Bold tab label on hover.
- Mimic font color in desktop version (black for active, blue for inactive, remove underline).
- Add vertical yellow bar on left side of active box.

See Courtney for any questions on styling and functionality.
Send test link to Courtney for QA and UX evaluation.

**Comment by kkoryaka** [comment]
@Courtney-Chittock figma prototype would be nice, but I think I can figure it out without it.

**Comment by Courtney-Chittock** [comment]
@kkoryaka I'm open to your design input on this.

**Comment by kkoryaka** [comment]
@Courtney-Chittock I have added mobile behavior to the tabs.
![Screen Shot 2022-06-23 at 2 30 58 PM](https://user-images.githubusercontent.com/31669748/175405870-954f5241-d787-4f35-90f1-de614a5091c5.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka this works for me! I will close this ticket.
